[build]
  base = "frontend"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/*"
to = "https://welbex.azurewebsites.net/:splat"
status = 200
